/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface BankTreasuryAbiInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "authorizeTable"
      | "availableForFloat"
      | "depositBankroll"
      | "depositFee"
      | "lockExposure"
      | "owner"
      | "releaseExposure"
      | "requestFloat"
      | "returnFloat"
      | "tables"
      | "totalBankroll"
      | "totalExposure"
      | "totalFloatOut"
      | "transferOwnership"
      | "updateTable"
      | "withdrawBankroll"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ExposureLocked"
      | "ExposureReleased"
      | "FeeReceived"
      | "FloatRequested"
      | "FloatReturned"
      | "OwnerDeposit"
      | "OwnerWithdraw"
      | "OwnershipTransferred"
      | "TableAuthorized"
      | "TableUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "authorizeTable",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "availableForFloat",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "depositBankroll",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "depositFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lockExposure",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "releaseExposure",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "requestFloat",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "returnFloat",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "tables", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "totalBankroll",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalExposure",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalFloatOut",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateTable",
    values: [AddressLike, BigNumberish, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawBankroll",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "authorizeTable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "availableForFloat",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositBankroll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "depositFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lockExposure",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "releaseExposure",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestFloat",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "returnFloat",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tables", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalBankroll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalExposure",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalFloatOut",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateTable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawBankroll",
    data: BytesLike
  ): Result;
}

export namespace ExposureLockedEvent {
  export type InputTuple = [
    table: AddressLike,
    delta: BigNumberish,
    newExposure: BigNumberish,
    total: BigNumberish
  ];
  export type OutputTuple = [
    table: string,
    delta: bigint,
    newExposure: bigint,
    total: bigint
  ];
  export interface OutputObject {
    table: string;
    delta: bigint;
    newExposure: bigint;
    total: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ExposureReleasedEvent {
  export type InputTuple = [
    table: AddressLike,
    delta: BigNumberish,
    newExposure: BigNumberish,
    total: BigNumberish
  ];
  export type OutputTuple = [
    table: string,
    delta: bigint,
    newExposure: bigint,
    total: bigint
  ];
  export interface OutputObject {
    table: string;
    delta: bigint;
    newExposure: bigint;
    total: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeeReceivedEvent {
  export type InputTuple = [
    table: AddressLike,
    amount: BigNumberish,
    cumulative: BigNumberish
  ];
  export type OutputTuple = [table: string, amount: bigint, cumulative: bigint];
  export interface OutputObject {
    table: string;
    amount: bigint;
    cumulative: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FloatRequestedEvent {
  export type InputTuple = [
    table: AddressLike,
    amount: BigNumberish,
    tableFloat: BigNumberish,
    total: BigNumberish
  ];
  export type OutputTuple = [
    table: string,
    amount: bigint,
    tableFloat: bigint,
    total: bigint
  ];
  export interface OutputObject {
    table: string;
    amount: bigint;
    tableFloat: bigint;
    total: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FloatReturnedEvent {
  export type InputTuple = [
    table: AddressLike,
    amount: BigNumberish,
    tableFloat: BigNumberish,
    total: BigNumberish
  ];
  export type OutputTuple = [
    table: string,
    amount: bigint,
    tableFloat: bigint,
    total: bigint
  ];
  export interface OutputObject {
    table: string;
    amount: bigint;
    tableFloat: bigint;
    total: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnerDepositEvent {
  export type InputTuple = [from: AddressLike, amount: BigNumberish];
  export type OutputTuple = [from: string, amount: bigint];
  export interface OutputObject {
    from: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnerWithdrawEvent {
  export type InputTuple = [to: AddressLike, amount: BigNumberish];
  export type OutputTuple = [to: string, amount: bigint];
  export interface OutputObject {
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [prev: AddressLike, next: AddressLike];
  export type OutputTuple = [prev: string, next: string];
  export interface OutputObject {
    prev: string;
    next: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TableAuthorizedEvent {
  export type InputTuple = [
    table: AddressLike,
    maxExposure: BigNumberish,
    floatLimit: BigNumberish
  ];
  export type OutputTuple = [
    table: string,
    maxExposure: bigint,
    floatLimit: bigint
  ];
  export interface OutputObject {
    table: string;
    maxExposure: bigint;
    floatLimit: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TableUpdatedEvent {
  export type InputTuple = [
    table: AddressLike,
    maxExposure: BigNumberish,
    floatLimit: BigNumberish,
    allowed: boolean
  ];
  export type OutputTuple = [
    table: string,
    maxExposure: bigint,
    floatLimit: bigint,
    allowed: boolean
  ];
  export interface OutputObject {
    table: string;
    maxExposure: bigint;
    floatLimit: bigint;
    allowed: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BankTreasuryAbi extends BaseContract {
  connect(runner?: ContractRunner | null): BankTreasuryAbi;
  waitForDeployment(): Promise<this>;

  interface: BankTreasuryAbiInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  authorizeTable: TypedContractMethod<
    [table: AddressLike, maxExposure: BigNumberish, floatLimit: BigNumberish],
    [void],
    "nonpayable"
  >;

  availableForFloat: TypedContractMethod<[], [bigint], "view">;

  depositBankroll: TypedContractMethod<[], [void], "payable">;

  depositFee: TypedContractMethod<[], [void], "payable">;

  lockExposure: TypedContractMethod<
    [delta: BigNumberish],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  releaseExposure: TypedContractMethod<
    [delta: BigNumberish],
    [void],
    "nonpayable"
  >;

  requestFloat: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  returnFloat: TypedContractMethod<[], [void], "payable">;

  tables: TypedContractMethod<
    [arg0: AddressLike],
    [
      [boolean, bigint, bigint, bigint, bigint, bigint] & {
        allowed: boolean;
        maxExposure: bigint;
        floatLimit: bigint;
        exposure: bigint;
        floatOut: bigint;
        feesPaid: bigint;
      }
    ],
    "view"
  >;

  totalBankroll: TypedContractMethod<[], [bigint], "view">;

  totalExposure: TypedContractMethod<[], [bigint], "view">;

  totalFloatOut: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [next: AddressLike],
    [void],
    "nonpayable"
  >;

  updateTable: TypedContractMethod<
    [
      table: AddressLike,
      maxExposure: BigNumberish,
      floatLimit: BigNumberish,
      allowed: boolean
    ],
    [void],
    "nonpayable"
  >;

  withdrawBankroll: TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "authorizeTable"
  ): TypedContractMethod<
    [table: AddressLike, maxExposure: BigNumberish, floatLimit: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "availableForFloat"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "depositBankroll"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "depositFee"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "lockExposure"
  ): TypedContractMethod<[delta: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "releaseExposure"
  ): TypedContractMethod<[delta: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requestFloat"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "returnFloat"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "tables"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [boolean, bigint, bigint, bigint, bigint, bigint] & {
        allowed: boolean;
        maxExposure: bigint;
        floatLimit: bigint;
        exposure: bigint;
        floatOut: bigint;
        feesPaid: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "totalBankroll"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalExposure"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalFloatOut"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[next: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateTable"
  ): TypedContractMethod<
    [
      table: AddressLike,
      maxExposure: BigNumberish,
      floatLimit: BigNumberish,
      allowed: boolean
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdrawBankroll"
  ): TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ExposureLocked"
  ): TypedContractEvent<
    ExposureLockedEvent.InputTuple,
    ExposureLockedEvent.OutputTuple,
    ExposureLockedEvent.OutputObject
  >;
  getEvent(
    key: "ExposureReleased"
  ): TypedContractEvent<
    ExposureReleasedEvent.InputTuple,
    ExposureReleasedEvent.OutputTuple,
    ExposureReleasedEvent.OutputObject
  >;
  getEvent(
    key: "FeeReceived"
  ): TypedContractEvent<
    FeeReceivedEvent.InputTuple,
    FeeReceivedEvent.OutputTuple,
    FeeReceivedEvent.OutputObject
  >;
  getEvent(
    key: "FloatRequested"
  ): TypedContractEvent<
    FloatRequestedEvent.InputTuple,
    FloatRequestedEvent.OutputTuple,
    FloatRequestedEvent.OutputObject
  >;
  getEvent(
    key: "FloatReturned"
  ): TypedContractEvent<
    FloatReturnedEvent.InputTuple,
    FloatReturnedEvent.OutputTuple,
    FloatReturnedEvent.OutputObject
  >;
  getEvent(
    key: "OwnerDeposit"
  ): TypedContractEvent<
    OwnerDepositEvent.InputTuple,
    OwnerDepositEvent.OutputTuple,
    OwnerDepositEvent.OutputObject
  >;
  getEvent(
    key: "OwnerWithdraw"
  ): TypedContractEvent<
    OwnerWithdrawEvent.InputTuple,
    OwnerWithdrawEvent.OutputTuple,
    OwnerWithdrawEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "TableAuthorized"
  ): TypedContractEvent<
    TableAuthorizedEvent.InputTuple,
    TableAuthorizedEvent.OutputTuple,
    TableAuthorizedEvent.OutputObject
  >;
  getEvent(
    key: "TableUpdated"
  ): TypedContractEvent<
    TableUpdatedEvent.InputTuple,
    TableUpdatedEvent.OutputTuple,
    TableUpdatedEvent.OutputObject
  >;

  filters: {
    "ExposureLocked(address,uint256,uint256,uint256)": TypedContractEvent<
      ExposureLockedEvent.InputTuple,
      ExposureLockedEvent.OutputTuple,
      ExposureLockedEvent.OutputObject
    >;
    ExposureLocked: TypedContractEvent<
      ExposureLockedEvent.InputTuple,
      ExposureLockedEvent.OutputTuple,
      ExposureLockedEvent.OutputObject
    >;

    "ExposureReleased(address,uint256,uint256,uint256)": TypedContractEvent<
      ExposureReleasedEvent.InputTuple,
      ExposureReleasedEvent.OutputTuple,
      ExposureReleasedEvent.OutputObject
    >;
    ExposureReleased: TypedContractEvent<
      ExposureReleasedEvent.InputTuple,
      ExposureReleasedEvent.OutputTuple,
      ExposureReleasedEvent.OutputObject
    >;

    "FeeReceived(address,uint256,uint256)": TypedContractEvent<
      FeeReceivedEvent.InputTuple,
      FeeReceivedEvent.OutputTuple,
      FeeReceivedEvent.OutputObject
    >;
    FeeReceived: TypedContractEvent<
      FeeReceivedEvent.InputTuple,
      FeeReceivedEvent.OutputTuple,
      FeeReceivedEvent.OutputObject
    >;

    "FloatRequested(address,uint256,uint256,uint256)": TypedContractEvent<
      FloatRequestedEvent.InputTuple,
      FloatRequestedEvent.OutputTuple,
      FloatRequestedEvent.OutputObject
    >;
    FloatRequested: TypedContractEvent<
      FloatRequestedEvent.InputTuple,
      FloatRequestedEvent.OutputTuple,
      FloatRequestedEvent.OutputObject
    >;

    "FloatReturned(address,uint256,uint256,uint256)": TypedContractEvent<
      FloatReturnedEvent.InputTuple,
      FloatReturnedEvent.OutputTuple,
      FloatReturnedEvent.OutputObject
    >;
    FloatReturned: TypedContractEvent<
      FloatReturnedEvent.InputTuple,
      FloatReturnedEvent.OutputTuple,
      FloatReturnedEvent.OutputObject
    >;

    "OwnerDeposit(address,uint256)": TypedContractEvent<
      OwnerDepositEvent.InputTuple,
      OwnerDepositEvent.OutputTuple,
      OwnerDepositEvent.OutputObject
    >;
    OwnerDeposit: TypedContractEvent<
      OwnerDepositEvent.InputTuple,
      OwnerDepositEvent.OutputTuple,
      OwnerDepositEvent.OutputObject
    >;

    "OwnerWithdraw(address,uint256)": TypedContractEvent<
      OwnerWithdrawEvent.InputTuple,
      OwnerWithdrawEvent.OutputTuple,
      OwnerWithdrawEvent.OutputObject
    >;
    OwnerWithdraw: TypedContractEvent<
      OwnerWithdrawEvent.InputTuple,
      OwnerWithdrawEvent.OutputTuple,
      OwnerWithdrawEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "TableAuthorized(address,uint256,uint256)": TypedContractEvent<
      TableAuthorizedEvent.InputTuple,
      TableAuthorizedEvent.OutputTuple,
      TableAuthorizedEvent.OutputObject
    >;
    TableAuthorized: TypedContractEvent<
      TableAuthorizedEvent.InputTuple,
      TableAuthorizedEvent.OutputTuple,
      TableAuthorizedEvent.OutputObject
    >;

    "TableUpdated(address,uint256,uint256,bool)": TypedContractEvent<
      TableUpdatedEvent.InputTuple,
      TableUpdatedEvent.OutputTuple,
      TableUpdatedEvent.OutputObject
    >;
    TableUpdated: TypedContractEvent<
      TableUpdatedEvent.InputTuple,
      TableUpdatedEvent.OutputTuple,
      TableUpdatedEvent.OutputObject
    >;
  };
}
