/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace Blackjack {
  export type CardStruct = { value: BigNumberish; suit: BigNumberish };

  export type CardStructOutput = [value: bigint, suit: bigint] & {
    value: bigint;
    suit: bigint;
  };

  export type HandStruct = {
    cards: Blackjack.CardStruct[];
    total: BigNumberish;
    hasUsableAce: boolean;
  };

  export type HandStructOutput = [
    cards: Blackjack.CardStructOutput[],
    total: bigint,
    hasUsableAce: boolean
  ] & {
    cards: Blackjack.CardStructOutput[];
    total: bigint;
    hasUsableAce: boolean;
  };
}

export interface BlackjackAbiInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "FEE_PERCENT"
      | "MAX_BET"
      | "MAX_PLAYERS"
      | "MIN_BET"
      | "bank"
      | "commitAndStart"
      | "commitPlayer"
      | "crRandom"
      | "currentGameId"
      | "games"
      | "getDealerHand"
      | "getDealerVisibleCard"
      | "getGameInfo"
      | "getPlayerHand"
      | "getPlayerStatus"
      | "hit"
      | "house"
      | "joinGame"
      | "revealAndDeal"
      | "stand"
      | "startGame"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CardDealt"
      | "CommitCountdownStart"
      | "DealerCardDealt"
      | "GameResolved"
      | "GameStarted"
      | "PlayerAction"
      | "PlayerJoined"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "FEE_PERCENT",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "MAX_BET", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "MAX_PLAYERS",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "MIN_BET", values?: undefined): string;
  encodeFunctionData(functionFragment: "bank", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "commitAndStart",
    values: [BigNumberish, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "commitPlayer",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "crRandom", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "currentGameId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "games", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "getDealerHand",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDealerVisibleCard",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getGameInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPlayerHand",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPlayerStatus",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "hit", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "house", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "joinGame",
    values: [BigNumberish, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "revealAndDeal",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "stand", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "startGame", values?: undefined): string;
  encodeFunctionData(functionFragment: "withdraw", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "FEE_PERCENT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "MAX_BET", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "MAX_PLAYERS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "MIN_BET", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "bank", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "commitAndStart",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "commitPlayer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "crRandom", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "currentGameId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "games", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getDealerHand",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDealerVisibleCard",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGameInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPlayerHand",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPlayerStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "house", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "joinGame", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "revealAndDeal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "stand", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "startGame", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace CardDealtEvent {
  export type InputTuple = [
    gameId: BigNumberish,
    player: AddressLike,
    value: BigNumberish,
    suit: BigNumberish
  ];
  export type OutputTuple = [
    gameId: bigint,
    player: string,
    value: bigint,
    suit: bigint
  ];
  export interface OutputObject {
    gameId: bigint;
    player: string;
    value: bigint;
    suit: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CommitCountdownStartEvent {
  export type InputTuple = [gameId: BigNumberish];
  export type OutputTuple = [gameId: bigint];
  export interface OutputObject {
    gameId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DealerCardDealtEvent {
  export type InputTuple = [
    gameId: BigNumberish,
    value: BigNumberish,
    suit: BigNumberish,
    hidden: boolean
  ];
  export type OutputTuple = [
    gameId: bigint,
    value: bigint,
    suit: bigint,
    hidden: boolean
  ];
  export interface OutputObject {
    gameId: bigint;
    value: bigint;
    suit: bigint;
    hidden: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GameResolvedEvent {
  export type InputTuple = [
    gameId: BigNumberish,
    player: AddressLike,
    won: boolean,
    payout: BigNumberish
  ];
  export type OutputTuple = [
    gameId: bigint,
    player: string,
    won: boolean,
    payout: bigint
  ];
  export interface OutputObject {
    gameId: bigint;
    player: string;
    won: boolean;
    payout: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GameStartedEvent {
  export type InputTuple = [gameId: BigNumberish];
  export type OutputTuple = [gameId: bigint];
  export interface OutputObject {
    gameId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlayerActionEvent {
  export type InputTuple = [
    gameId: BigNumberish,
    player: AddressLike,
    action: string
  ];
  export type OutputTuple = [gameId: bigint, player: string, action: string];
  export interface OutputObject {
    gameId: bigint;
    player: string;
    action: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlayerJoinedEvent {
  export type InputTuple = [
    gameId: BigNumberish,
    player: AddressLike,
    bet: BigNumberish
  ];
  export type OutputTuple = [gameId: bigint, player: string, bet: bigint];
  export interface OutputObject {
    gameId: bigint;
    player: string;
    bet: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BlackjackAbi extends BaseContract {
  connect(runner?: ContractRunner | null): BlackjackAbi;
  waitForDeployment(): Promise<this>;

  interface: BlackjackAbiInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  FEE_PERCENT: TypedContractMethod<[], [bigint], "view">;

  MAX_BET: TypedContractMethod<[], [bigint], "view">;

  MAX_PLAYERS: TypedContractMethod<[], [bigint], "view">;

  MIN_BET: TypedContractMethod<[], [bigint], "view">;

  bank: TypedContractMethod<[], [string], "view">;

  commitAndStart: TypedContractMethod<
    [gameId: BigNumberish, dealerHash: BytesLike, randomNumber: BigNumberish],
    [void],
    "nonpayable"
  >;

  commitPlayer: TypedContractMethod<[gameId: BigNumberish], [void], "payable">;

  crRandom: TypedContractMethod<[], [string], "view">;

  currentGameId: TypedContractMethod<[], [bigint], "view">;

  games: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, Blackjack.HandStructOutput, bigint, bigint] & {
        rngRoundId: bigint;
        state: bigint;
        dealerHand: Blackjack.HandStructOutput;
        cardCounter: bigint;
        currentPlayerIndex: bigint;
      }
    ],
    "view"
  >;

  getDealerHand: TypedContractMethod<
    [gameId: BigNumberish],
    [
      [Blackjack.CardStructOutput[], bigint] & {
        cards: Blackjack.CardStructOutput[];
        total: bigint;
      }
    ],
    "view"
  >;

  getDealerVisibleCard: TypedContractMethod<
    [gameId: BigNumberish],
    [Blackjack.CardStructOutput],
    "view"
  >;

  getGameInfo: TypedContractMethod<
    [gameId: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        state: bigint;
        playerCount: bigint;
        currentPlayer: bigint;
      }
    ],
    "view"
  >;

  getPlayerHand: TypedContractMethod<
    [gameId: BigNumberish, player: AddressLike],
    [
      [Blackjack.CardStructOutput[], bigint] & {
        cards: Blackjack.CardStructOutput[];
        total: bigint;
      }
    ],
    "view"
  >;

  getPlayerStatus: TypedContractMethod<
    [gameId: BigNumberish, player: AddressLike],
    [[bigint, bigint] & { status: bigint; bet: bigint }],
    "view"
  >;

  hit: TypedContractMethod<[gameId: BigNumberish], [void], "nonpayable">;

  house: TypedContractMethod<[], [string], "view">;

  joinGame: TypedContractMethod<
    [gameId: BigNumberish, playerHash: BytesLike, randomNumber: BigNumberish],
    [void],
    "payable"
  >;

  revealAndDeal: TypedContractMethod<
    [gameId: BigNumberish, dealerSecret: BigNumberish],
    [void],
    "nonpayable"
  >;

  stand: TypedContractMethod<[gameId: BigNumberish], [void], "nonpayable">;

  startGame: TypedContractMethod<[], [bigint], "nonpayable">;

  withdraw: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "FEE_PERCENT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_BET"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_PLAYERS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_BET"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "bank"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "commitAndStart"
  ): TypedContractMethod<
    [gameId: BigNumberish, dealerHash: BytesLike, randomNumber: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "commitPlayer"
  ): TypedContractMethod<[gameId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "crRandom"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "currentGameId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "games"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, Blackjack.HandStructOutput, bigint, bigint] & {
        rngRoundId: bigint;
        state: bigint;
        dealerHand: Blackjack.HandStructOutput;
        cardCounter: bigint;
        currentPlayerIndex: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getDealerHand"
  ): TypedContractMethod<
    [gameId: BigNumberish],
    [
      [Blackjack.CardStructOutput[], bigint] & {
        cards: Blackjack.CardStructOutput[];
        total: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getDealerVisibleCard"
  ): TypedContractMethod<
    [gameId: BigNumberish],
    [Blackjack.CardStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getGameInfo"
  ): TypedContractMethod<
    [gameId: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        state: bigint;
        playerCount: bigint;
        currentPlayer: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPlayerHand"
  ): TypedContractMethod<
    [gameId: BigNumberish, player: AddressLike],
    [
      [Blackjack.CardStructOutput[], bigint] & {
        cards: Blackjack.CardStructOutput[];
        total: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPlayerStatus"
  ): TypedContractMethod<
    [gameId: BigNumberish, player: AddressLike],
    [[bigint, bigint] & { status: bigint; bet: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "hit"
  ): TypedContractMethod<[gameId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "house"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "joinGame"
  ): TypedContractMethod<
    [gameId: BigNumberish, playerHash: BytesLike, randomNumber: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "revealAndDeal"
  ): TypedContractMethod<
    [gameId: BigNumberish, dealerSecret: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "stand"
  ): TypedContractMethod<[gameId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "startGame"
  ): TypedContractMethod<[], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "CardDealt"
  ): TypedContractEvent<
    CardDealtEvent.InputTuple,
    CardDealtEvent.OutputTuple,
    CardDealtEvent.OutputObject
  >;
  getEvent(
    key: "CommitCountdownStart"
  ): TypedContractEvent<
    CommitCountdownStartEvent.InputTuple,
    CommitCountdownStartEvent.OutputTuple,
    CommitCountdownStartEvent.OutputObject
  >;
  getEvent(
    key: "DealerCardDealt"
  ): TypedContractEvent<
    DealerCardDealtEvent.InputTuple,
    DealerCardDealtEvent.OutputTuple,
    DealerCardDealtEvent.OutputObject
  >;
  getEvent(
    key: "GameResolved"
  ): TypedContractEvent<
    GameResolvedEvent.InputTuple,
    GameResolvedEvent.OutputTuple,
    GameResolvedEvent.OutputObject
  >;
  getEvent(
    key: "GameStarted"
  ): TypedContractEvent<
    GameStartedEvent.InputTuple,
    GameStartedEvent.OutputTuple,
    GameStartedEvent.OutputObject
  >;
  getEvent(
    key: "PlayerAction"
  ): TypedContractEvent<
    PlayerActionEvent.InputTuple,
    PlayerActionEvent.OutputTuple,
    PlayerActionEvent.OutputObject
  >;
  getEvent(
    key: "PlayerJoined"
  ): TypedContractEvent<
    PlayerJoinedEvent.InputTuple,
    PlayerJoinedEvent.OutputTuple,
    PlayerJoinedEvent.OutputObject
  >;

  filters: {
    "CardDealt(uint256,address,uint8,uint8)": TypedContractEvent<
      CardDealtEvent.InputTuple,
      CardDealtEvent.OutputTuple,
      CardDealtEvent.OutputObject
    >;
    CardDealt: TypedContractEvent<
      CardDealtEvent.InputTuple,
      CardDealtEvent.OutputTuple,
      CardDealtEvent.OutputObject
    >;

    "CommitCountdownStart(uint256)": TypedContractEvent<
      CommitCountdownStartEvent.InputTuple,
      CommitCountdownStartEvent.OutputTuple,
      CommitCountdownStartEvent.OutputObject
    >;
    CommitCountdownStart: TypedContractEvent<
      CommitCountdownStartEvent.InputTuple,
      CommitCountdownStartEvent.OutputTuple,
      CommitCountdownStartEvent.OutputObject
    >;

    "DealerCardDealt(uint256,uint8,uint8,bool)": TypedContractEvent<
      DealerCardDealtEvent.InputTuple,
      DealerCardDealtEvent.OutputTuple,
      DealerCardDealtEvent.OutputObject
    >;
    DealerCardDealt: TypedContractEvent<
      DealerCardDealtEvent.InputTuple,
      DealerCardDealtEvent.OutputTuple,
      DealerCardDealtEvent.OutputObject
    >;

    "GameResolved(uint256,address,bool,uint256)": TypedContractEvent<
      GameResolvedEvent.InputTuple,
      GameResolvedEvent.OutputTuple,
      GameResolvedEvent.OutputObject
    >;
    GameResolved: TypedContractEvent<
      GameResolvedEvent.InputTuple,
      GameResolvedEvent.OutputTuple,
      GameResolvedEvent.OutputObject
    >;

    "GameStarted(uint256)": TypedContractEvent<
      GameStartedEvent.InputTuple,
      GameStartedEvent.OutputTuple,
      GameStartedEvent.OutputObject
    >;
    GameStarted: TypedContractEvent<
      GameStartedEvent.InputTuple,
      GameStartedEvent.OutputTuple,
      GameStartedEvent.OutputObject
    >;

    "PlayerAction(uint256,address,string)": TypedContractEvent<
      PlayerActionEvent.InputTuple,
      PlayerActionEvent.OutputTuple,
      PlayerActionEvent.OutputObject
    >;
    PlayerAction: TypedContractEvent<
      PlayerActionEvent.InputTuple,
      PlayerActionEvent.OutputTuple,
      PlayerActionEvent.OutputObject
    >;

    "PlayerJoined(uint256,address,uint256)": TypedContractEvent<
      PlayerJoinedEvent.InputTuple,
      PlayerJoinedEvent.OutputTuple,
      PlayerJoinedEvent.OutputObject
    >;
    PlayerJoined: TypedContractEvent<
      PlayerJoinedEvent.InputTuple,
      PlayerJoinedEvent.OutputTuple,
      PlayerJoinedEvent.OutputObject
    >;
  };
}
