/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface CommitRevealRandomAbiInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "commit"
      | "commitDeadline"
      | "commitments"
      | "dealer"
      | "finalRandom"
      | "gamePlayers"
      | "generateFinalRandom"
      | "getCommitment"
      | "getFinalRandom"
      | "hasRevealed"
      | "phase"
      | "resetGame"
      | "reveal"
      | "revealDeadline"
      | "roundId"
      | "start"
      | "startRevealPhase"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Committed"
      | "RandomGenerated"
      | "Revealed"
      | "Started"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "commit",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "commitDeadline",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "commitments",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "dealer", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "finalRandom",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "gamePlayers",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "generateFinalRandom",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCommitment",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getFinalRandom",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRevealed",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "phase", values?: undefined): string;
  encodeFunctionData(functionFragment: "resetGame", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "reveal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "revealDeadline",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "roundId", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "start",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "startRevealPhase",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "commit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "commitDeadline",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "commitments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "dealer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "finalRandom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "gamePlayers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "generateFinalRandom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCommitment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFinalRandom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasRevealed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "phase", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "resetGame", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "reveal", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "revealDeadline",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "roundId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "start", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "startRevealPhase",
    data: BytesLike
  ): Result;
}

export namespace CommittedEvent {
  export type InputTuple = [gameId: BigNumberish, player: AddressLike];
  export type OutputTuple = [gameId: bigint, player: string];
  export interface OutputObject {
    gameId: bigint;
    player: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RandomGeneratedEvent {
  export type InputTuple = [gameId: BigNumberish, randomNumber: BigNumberish];
  export type OutputTuple = [gameId: bigint, randomNumber: bigint];
  export interface OutputObject {
    gameId: bigint;
    randomNumber: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RevealedEvent {
  export type InputTuple = [
    gameId: BigNumberish,
    player: AddressLike,
    randomNumber: BigNumberish
  ];
  export type OutputTuple = [
    gameId: bigint,
    player: string,
    randomNumber: bigint
  ];
  export interface OutputObject {
    gameId: bigint;
    player: string;
    randomNumber: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StartedEvent {
  export type InputTuple = [
    gameId: BigNumberish,
    commitDeadline: BigNumberish,
    revealDeadline: BigNumberish
  ];
  export type OutputTuple = [
    gameId: bigint,
    commitDeadline: bigint,
    revealDeadline: bigint
  ];
  export interface OutputObject {
    gameId: bigint;
    commitDeadline: bigint;
    revealDeadline: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CommitRevealRandomAbi extends BaseContract {
  connect(runner?: ContractRunner | null): CommitRevealRandomAbi;
  waitForDeployment(): Promise<this>;

  interface: CommitRevealRandomAbiInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  commit: TypedContractMethod<
    [_commitHash: BytesLike, randomNumber: BigNumberish],
    [void],
    "nonpayable"
  >;

  commitDeadline: TypedContractMethod<[], [bigint], "view">;

  commitments: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [
      [string, bigint, bigint, boolean, boolean] & {
        commitHash: string;
        randomNumber: bigint;
        secret: bigint;
        committed: boolean;
        revealed: boolean;
      }
    ],
    "view"
  >;

  dealer: TypedContractMethod<[], [string], "view">;

  finalRandom: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  gamePlayers: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [string],
    "view"
  >;

  generateFinalRandom: TypedContractMethod<[], [void], "nonpayable">;

  getCommitment: TypedContractMethod<
    [_gameId: BigNumberish, _player: AddressLike],
    [
      [string, bigint, boolean, boolean] & {
        commitHash: string;
        randomNumber: bigint;
        committed: boolean;
        revealed: boolean;
      }
    ],
    "view"
  >;

  getFinalRandom: TypedContractMethod<[id: BigNumberish], [bigint], "view">;

  hasRevealed: TypedContractMethod<[_player: AddressLike], [boolean], "view">;

  phase: TypedContractMethod<[], [bigint], "view">;

  resetGame: TypedContractMethod<[], [void], "nonpayable">;

  reveal: TypedContractMethod<[_secret: BigNumberish], [void], "nonpayable">;

  revealDeadline: TypedContractMethod<[], [bigint], "view">;

  roundId: TypedContractMethod<[], [bigint], "view">;

  start: TypedContractMethod<
    [_commitDuration: BigNumberish, _revealDuration: BigNumberish],
    [void],
    "nonpayable"
  >;

  startRevealPhase: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "commit"
  ): TypedContractMethod<
    [_commitHash: BytesLike, randomNumber: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "commitDeadline"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "commitments"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [
      [string, bigint, bigint, boolean, boolean] & {
        commitHash: string;
        randomNumber: bigint;
        secret: bigint;
        committed: boolean;
        revealed: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "dealer"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "finalRandom"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "gamePlayers"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "generateFinalRandom"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getCommitment"
  ): TypedContractMethod<
    [_gameId: BigNumberish, _player: AddressLike],
    [
      [string, bigint, boolean, boolean] & {
        commitHash: string;
        randomNumber: bigint;
        committed: boolean;
        revealed: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getFinalRandom"
  ): TypedContractMethod<[id: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "hasRevealed"
  ): TypedContractMethod<[_player: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "phase"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "resetGame"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "reveal"
  ): TypedContractMethod<[_secret: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revealDeadline"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "roundId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "start"
  ): TypedContractMethod<
    [_commitDuration: BigNumberish, _revealDuration: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "startRevealPhase"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "Committed"
  ): TypedContractEvent<
    CommittedEvent.InputTuple,
    CommittedEvent.OutputTuple,
    CommittedEvent.OutputObject
  >;
  getEvent(
    key: "RandomGenerated"
  ): TypedContractEvent<
    RandomGeneratedEvent.InputTuple,
    RandomGeneratedEvent.OutputTuple,
    RandomGeneratedEvent.OutputObject
  >;
  getEvent(
    key: "Revealed"
  ): TypedContractEvent<
    RevealedEvent.InputTuple,
    RevealedEvent.OutputTuple,
    RevealedEvent.OutputObject
  >;
  getEvent(
    key: "Started"
  ): TypedContractEvent<
    StartedEvent.InputTuple,
    StartedEvent.OutputTuple,
    StartedEvent.OutputObject
  >;

  filters: {
    "Committed(uint256,address)": TypedContractEvent<
      CommittedEvent.InputTuple,
      CommittedEvent.OutputTuple,
      CommittedEvent.OutputObject
    >;
    Committed: TypedContractEvent<
      CommittedEvent.InputTuple,
      CommittedEvent.OutputTuple,
      CommittedEvent.OutputObject
    >;

    "RandomGenerated(uint256,uint256)": TypedContractEvent<
      RandomGeneratedEvent.InputTuple,
      RandomGeneratedEvent.OutputTuple,
      RandomGeneratedEvent.OutputObject
    >;
    RandomGenerated: TypedContractEvent<
      RandomGeneratedEvent.InputTuple,
      RandomGeneratedEvent.OutputTuple,
      RandomGeneratedEvent.OutputObject
    >;

    "Revealed(uint256,address,uint256)": TypedContractEvent<
      RevealedEvent.InputTuple,
      RevealedEvent.OutputTuple,
      RevealedEvent.OutputObject
    >;
    Revealed: TypedContractEvent<
      RevealedEvent.InputTuple,
      RevealedEvent.OutputTuple,
      RevealedEvent.OutputObject
    >;

    "Started(uint256,uint256,uint256)": TypedContractEvent<
      StartedEvent.InputTuple,
      StartedEvent.OutputTuple,
      StartedEvent.OutputObject
    >;
    Started: TypedContractEvent<
      StartedEvent.InputTuple,
      StartedEvent.OutputTuple,
      StartedEvent.OutputObject
    >;
  };
}
