/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  BankTreasuryAbi,
  BankTreasuryAbiInterface,
} from "../BankTreasuryAbi";

const _abi = [
  {
    type: "constructor",
    inputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "fallback",
    stateMutability: "payable",
  },
  {
    type: "receive",
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "authorizeTable",
    inputs: [
      {
        name: "table",
        type: "address",
        internalType: "address",
      },
      {
        name: "maxExposure",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "floatLimit",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "availableForFloat",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "depositBankroll",
    inputs: [],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "depositFee",
    inputs: [],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "lockExposure",
    inputs: [
      {
        name: "delta",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "owner",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "releaseExposure",
    inputs: [
      {
        name: "delta",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "requestFloat",
    inputs: [
      {
        name: "amount",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "returnFloat",
    inputs: [],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "tables",
    inputs: [
      {
        name: "",
        type: "address",
        internalType: "address",
      },
    ],
    outputs: [
      {
        name: "allowed",
        type: "bool",
        internalType: "bool",
      },
      {
        name: "maxExposure",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "floatLimit",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "exposure",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "floatOut",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "feesPaid",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "totalBankroll",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "totalExposure",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "totalFloatOut",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "transferOwnership",
    inputs: [
      {
        name: "next",
        type: "address",
        internalType: "address",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "updateTable",
    inputs: [
      {
        name: "table",
        type: "address",
        internalType: "address",
      },
      {
        name: "maxExposure",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "floatLimit",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "allowed",
        type: "bool",
        internalType: "bool",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "withdrawBankroll",
    inputs: [
      {
        name: "to",
        type: "address",
        internalType: "address payable",
      },
      {
        name: "amount",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "ExposureLocked",
    inputs: [
      {
        name: "table",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "delta",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "newExposure",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "total",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ExposureReleased",
    inputs: [
      {
        name: "table",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "delta",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "newExposure",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "total",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "FeeReceived",
    inputs: [
      {
        name: "table",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "cumulative",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "FloatRequested",
    inputs: [
      {
        name: "table",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "tableFloat",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "total",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "FloatReturned",
    inputs: [
      {
        name: "table",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "tableFloat",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "total",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "OwnerDeposit",
    inputs: [
      {
        name: "from",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "OwnerWithdraw",
    inputs: [
      {
        name: "to",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "OwnershipTransferred",
    inputs: [
      {
        name: "prev",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "next",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "TableAuthorized",
    inputs: [
      {
        name: "table",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "maxExposure",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "floatLimit",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "TableUpdated",
    inputs: [
      {
        name: "table",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "maxExposure",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "floatLimit",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "allowed",
        type: "bool",
        indexed: false,
        internalType: "bool",
      },
    ],
    anonymous: false,
  },
] as const;

export class BankTreasuryAbi__factory {
  static readonly abi = _abi;
  static createInterface(): BankTreasuryAbiInterface {
    return new Interface(_abi) as BankTreasuryAbiInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): BankTreasuryAbi {
    return new Contract(address, _abi, runner) as unknown as BankTreasuryAbi;
  }
}
