/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  CasinoScriptAbi,
  CasinoScriptAbiInterface,
} from "../CasinoScriptAbi";

const _abi = [
  {
    type: "function",
    name: "IS_SCRIPT",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "bool",
        internalType: "bool",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "bank",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "contract BankTreasury",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "rng",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "contract CommitRevealRandom",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "run",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setUp",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "table",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "contract Blackjack",
      },
    ],
    stateMutability: "view",
  },
] as const;

export class CasinoScriptAbi__factory {
  static readonly abi = _abi;
  static createInterface(): CasinoScriptAbiInterface {
    return new Interface(_abi) as CasinoScriptAbiInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): CasinoScriptAbi {
    return new Contract(address, _abi, runner) as unknown as CasinoScriptAbi;
  }
}
