/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  CommitRevealRandomAbi,
  CommitRevealRandomAbiInterface,
} from "../CommitRevealRandomAbi";

const _abi = [
  {
    type: "constructor",
    inputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "commit",
    inputs: [
      {
        name: "_commitHash",
        type: "bytes32",
        internalType: "bytes32",
      },
      {
        name: "randomNumber",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "commitDeadline",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "commitments",
    inputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "",
        type: "address",
        internalType: "address",
      },
    ],
    outputs: [
      {
        name: "commitHash",
        type: "bytes32",
        internalType: "bytes32",
      },
      {
        name: "randomNumber",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "secret",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "committed",
        type: "bool",
        internalType: "bool",
      },
      {
        name: "revealed",
        type: "bool",
        internalType: "bool",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "dealer",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "finalRandom",
    inputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "gamePlayers",
    inputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "generateFinalRandom",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getCommitment",
    inputs: [
      {
        name: "_gameId",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "_player",
        type: "address",
        internalType: "address",
      },
    ],
    outputs: [
      {
        name: "commitHash",
        type: "bytes32",
        internalType: "bytes32",
      },
      {
        name: "randomNumber",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "committed",
        type: "bool",
        internalType: "bool",
      },
      {
        name: "revealed",
        type: "bool",
        internalType: "bool",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getFinalRandom",
    inputs: [
      {
        name: "id",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "hasRevealed",
    inputs: [
      {
        name: "_player",
        type: "address",
        internalType: "address",
      },
    ],
    outputs: [
      {
        name: "",
        type: "bool",
        internalType: "bool",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "phase",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "uint8",
        internalType: "enum CommitRevealRandom.CRRPhase",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "resetGame",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "reveal",
    inputs: [
      {
        name: "_secret",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "revealDeadline",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "roundId",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "start",
    inputs: [
      {
        name: "_commitDuration",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "_revealDuration",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "startRevealPhase",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "Committed",
    inputs: [
      {
        name: "gameId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "player",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "RandomGenerated",
    inputs: [
      {
        name: "gameId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "randomNumber",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Revealed",
    inputs: [
      {
        name: "gameId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "player",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "randomNumber",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Started",
    inputs: [
      {
        name: "gameId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "commitDeadline",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "revealDeadline",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
] as const;

export class CommitRevealRandomAbi__factory {
  static readonly abi = _abi;
  static createInterface(): CommitRevealRandomAbiInterface {
    return new Interface(_abi) as CommitRevealRandomAbiInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): CommitRevealRandomAbi {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as CommitRevealRandomAbi;
  }
}
