/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { ScriptAbi, ScriptAbiInterface } from "../ScriptAbi";

const _abi = [
  {
    type: "function",
    name: "IS_SCRIPT",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "bool",
        internalType: "bool",
      },
    ],
    stateMutability: "view",
  },
] as const;

export class ScriptAbi__factory {
  static readonly abi = _abi;
  static createInterface(): ScriptAbiInterface {
    return new Interface(_abi) as ScriptAbiInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): ScriptAbi {
    return new Contract(address, _abi, runner) as unknown as ScriptAbi;
  }
}
