/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  StdStorageSafeAbi,
  StdStorageSafeAbiInterface,
} from "../StdStorageSafeAbi";

const _abi = [
  {
    type: "event",
    name: "SlotFound",
    inputs: [
      {
        name: "who",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "fsig",
        type: "bytes4",
        indexed: false,
        internalType: "bytes4",
      },
      {
        name: "keysHash",
        type: "bytes32",
        indexed: false,
        internalType: "bytes32",
      },
      {
        name: "slot",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "WARNING_UninitedSlot",
    inputs: [
      {
        name: "who",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "slot",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
] as const;

export class StdStorageSafeAbi__factory {
  static readonly abi = _abi;
  static createInterface(): StdStorageSafeAbiInterface {
    return new Interface(_abi) as StdStorageSafeAbiInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): StdStorageSafeAbi {
    return new Contract(address, _abi, runner) as unknown as StdStorageSafeAbi;
  }
}
